export const environment = {
  production: true,
  testCredentials: { customers: [] as { username: string; password: string }[] },
  apiUrl: "/api",
  useMockApi: false,
  appName: "E-Bank",
  version: "1.0.0",
  cloudinary: { cloudName: "", uploadPreset: "" },
  tokenKey: "digital-banking-token",
  endpoints: {
    auth: {
      login: "/auth/login",
      register: "/auth/register",
      refresh: "/auth/refresh",
      changePassword: "/auth/change-password",
      profile: "/auth/profile",
    },
    admin: {
      users: "/admin/users",
      accounts: "/admin/accounts",
      customers: "/admin/customers",
      usersByRole: "/admin/users/role",
      userStatus: "/admin/users",
      dashboard: "/admin/dashboard",
    },
    customer: {
      accounts: "/customer/accounts",
      transactions: "/customer/transactions",
      dashboard: "/customer/dashboard",
    },
    customers: "/customers",
    accounts: "/accounts",
    transactions: "/transactions",
    dashboard: "/dashboard",
    operations: {
      debit: "/accounts",
      credit: "/accounts",
      transfer: "/accounts",
      history: "/accounts",
    },
  },
};
