import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

async function login(page: Page, role: 'Admin' | 'Customer') {
  await page.goto('/auth/login');
  await page.getByRole('button', { name: role, exact: false }).click();
  await expect(page).toHaveURL(role === 'Admin' ? /\/admin\/dashboard/ : /\/customer\/dashboard/);
  await expect(page.locator('.bank-brand')).toHaveText('E-Bank');
}

async function assertNoOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
}

test('brand, password visibility and invalid login @smoke', async ({ page }) => {
  await page.goto('/auth/login');
  await expect(page).toHaveTitle(/E-Bank/);
  await expect(page.getByRole('heading', { name: 'Your personal space' })).toBeVisible();
  await page.locator('#username').fill('unknown.user');
  await page.locator('#password').fill('invalid-password');
  await page.getByRole('button', { name: 'Show password' }).click();
  await expect(page.locator('#password')).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: 'Hide password' }).click();
  await page.getByRole('button', { name: 'Sign In', exact: false }).click();
  await expect(page.locator('app-login [role="alert"]')).toBeVisible();
  await expect(page).toHaveURL(/auth\/login/);
  await assertNoOverflow(page);
});

test('login accessibility and registration navigation @smoke', async ({ page }) => {
  await page.goto('/auth/login');
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(result.violations).toEqual([]);
  await page.getByRole('link', { name: 'Sign up' }).click();
  await expect(page).toHaveURL(/auth\/register/);
  await expect(page.getByRole('heading', { name: 'Create Account' })).toBeVisible();
  await assertNoOverflow(page);
});

for (const role of ['Admin', 'Customer'] as const) {
  test(`${role} authenticates and logs out @smoke`, async ({ page }) => {
    await login(page, role);
    await page.getByRole('button', { name: 'Log out', exact: true }).click();
    await expect(page).toHaveURL(/auth\/login/);
    await page.goto(role === 'Admin' ? '/admin/accounts' : '/customer/accounts');
    await expect(page).toHaveURL(/auth\/login/);
  });
}

const routeSets = {
  Admin: ['/admin/dashboard','/admin/customers','/admin/customers/new','/admin/accounts','/admin/accounts/new','/admin/transactions','/admin/transfer','/admin/reports','/profile'],
  Customer: ['/customer/dashboard','/customer/accounts','/customer/accounts/new','/customer/deposit','/customer/debit','/customer/transfer','/customer/transaction-history','/profile'],
} as const;
for (const role of ['Admin','Customer'] as const) {
  test(`${role} routes render without runtime errors`, async ({ page }, testInfo) => {
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await login(page, role);
    const actions: Record<string, string[]> = {};
    for (const route of routeSets[role]) {
      await page.goto(route);
      await expect(page).toHaveURL(new RegExp(route + '$'));
      await expect(page.locator('main')).toBeVisible();
      await expect(page.locator('main h1, main h2').first()).toBeVisible();
      await assertNoOverflow(page);
      actions[route] = await page.locator('main button, main a, main input, main select').evaluateAll(elements => elements.map(e => (e.getAttribute('aria-label') || e.textContent || e.getAttribute('id') || '').trim()));
      await page.screenshot({ path: testInfo.outputPath(route.replaceAll('/', '-') + '.png'), fullPage: true });
    }
    await testInfo.attach('visible-actions', { body: JSON.stringify(actions, null, 2), contentType: 'application/json' });
    expect(errors).toEqual([]);
  });
}

test('reports are generated by the backend and downloaded', async ({ page }) => {
  await login(page, 'Admin');
  await page.goto('/admin/reports');
  for (const report of ['customer-summary','account-balance','transaction-analysis']) {
    await page.getByLabel('Report', { exact: true }).selectOption(report);
    if (report === 'transaction-analysis') await page.getByLabel('Period').selectOption({ label: 'Last 7 days' });
    const response = page.waitForResponse(r => r.url().includes(`/api/reports/${report}`));
    await page.getByRole('button', { name: 'Generate report' }).click();
    expect((await response).ok()).toBe(true);
    const download = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download JSON' }).click();
    expect((await download).suggestedFilename()).toBe(`e-bank-${report}.json`);
  }
});

test('customer is redirected away from administration', async ({ page }) => {
  await login(page, 'Customer');
  await page.goto('/admin/customers');
  await expect(page).toHaveURL(/unauthorized/);
});

test('credit updates the persisted account balance', async ({ page }) => {
  await login(page, 'Customer');
  await page.goto('/customer/deposit');
  await expect(page.locator('#accountId option')).not.toHaveCount(1);
  const accountId = await page.locator('#accountId option').nth(1).getAttribute('value');
  expect(accountId).toBeTruthy();
  const token = await page.evaluate(() => sessionStorage.getItem('digital-banking-token') || localStorage.getItem('digital-banking-token'));
  const headers = { Authorization: `Bearer ${token}` };
  const beforeResponse = await page.request.get(`/api/accounts/${accountId}`, { headers });
  expect(beforeResponse.ok()).toBe(true);
  const before = await beforeResponse.json();
  await page.getByLabel('Select Account').selectOption(accountId!);
  await page.getByLabel('Amount', { exact: true }).fill('1.25');
  await page.getByLabel('Description').fill(`E2E credit ${Date.now()}`);
  const mutation = page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('credit'));
  await page.locator('button[type="submit"]').click();
  expect((await mutation).ok()).toBe(true);
  await expect.poll(async () => {
    const after = await (await page.request.get(`/api/accounts/${accountId}`, { headers })).json();
    return Math.round((after.balance - before.balance) * 100);
  }).toBe(125);
});
