import { test, expect, Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { randomUUID } from 'node:crypto';

async function login(page: Page, role: 'Admin' | 'Customer') {
  await page.goto('/auth/login');
  await page.getByRole('button', { name: role, exact: false }).click();
  await expect(page).toHaveURL(role === 'Admin' ? /\/admin\/dashboard/ : /\/customer\/dashboard/);
  await expect(page.locator('.bank-brand')).toHaveText('E-Bank');
}

async function assertNoOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
}

test('brand, password visibility and invalid login @smoke', async ({ page }) => {
  await page.goto('/auth/login');
  await expect(page).toHaveTitle(/E-Bank/);
  await expect(page.getByRole('heading', { name: 'Your personal space' })).toBeVisible();
  await page.locator('#username').fill('unknown.user');
  await page.locator('#password').fill('invalid-password');
  await page.getByRole('button', { name: 'Show password' }).click();
  await expect(page.locator('#password')).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: 'Hide password' }).click();
  await page.getByRole('button', { name: 'Sign In', exact: false }).click();
  await expect(page.locator('app-login [role="alert"]')).toBeVisible();
  await expect(page).toHaveURL(/auth\/login/);
  await assertNoOverflow(page);
});

test('login accessibility and registration navigation @smoke', async ({ page }) => {
  await page.goto('/auth/login');
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(result.violations).toEqual([]);
  await page.getByRole('link', { name: 'Sign up' }).click();
  await expect(page).toHaveURL(/auth\/register/);
  await expect(page.getByRole('heading', { name: 'Create Account' })).toBeVisible();
  await assertNoOverflow(page);
});

for (const role of ['Admin', 'Customer'] as const) {
  test(`${role} authenticates and logs out @smoke`, async ({ page }) => {
    await login(page, role);
    await page.getByRole('button', { name: 'Log out', exact: true }).click();
    await expect(page).toHaveURL(/auth\/login/);
    await page.goto(role === 'Admin' ? '/admin/accounts' : '/customer/accounts');
    await expect(page).toHaveURL(/auth\/login/);
  });
}

const routeSets = {
  Admin: ['/admin/dashboard','/admin/customers','/admin/customers/new','/admin/accounts','/admin/accounts/new','/admin/transactions','/admin/transfer','/admin/reports','/profile'],
  Customer: ['/customer/dashboard','/customer/accounts','/customer/accounts/new','/customer/deposit','/customer/debit','/customer/transfer','/customer/transaction-history','/profile'],
} as const;
for (const role of ['Admin','Customer'] as const) {
  test(`${role} routes render without runtime errors`, async ({ page }, testInfo) => {
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await login(page, role);
    const actions: Record<string, string[]> = {};
    for (const route of routeSets[role]) {
      await page.goto(route);
      await expect(page).toHaveURL(new RegExp(route + '$'));
      await expect(page.locator('main')).toBeVisible();
      await expect(page.getByRole('main').getByRole('heading').first()).toBeVisible();
      await assertNoOverflow(page);
      actions[route] = await page.locator('main button, main a, main input, main select').evaluateAll(elements => elements.map(e => (e.getAttribute('aria-label') || e.textContent || e.getAttribute('id') || '').trim()));
      await page.screenshot({ path: testInfo.outputPath(route.replaceAll('/', '-') + '.png'), fullPage: true });
    }
    await testInfo.attach('visible-actions', { body: JSON.stringify(actions, null, 2), contentType: 'application/json' });
    expect(errors).toEqual([]);
  });
}

test('reports are generated by the backend and downloaded', async ({ page }) => {
  await login(page, 'Admin');
  await page.goto('/admin/reports');
  for (const report of ['customer-summary','account-balance','transaction-analysis']) {
    await page.getByLabel('Report', { exact: true }).selectOption(report);
    if (report === 'transaction-analysis') await page.getByLabel('Period').selectOption({ label: 'Last 7 days' });
    const response = page.waitForResponse(r => r.url().includes(`/api/reports/${report}`));
    await page.getByRole('button', { name: 'Generate report' }).click();
    expect((await response).ok()).toBe(true);
    const download = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download PDF' }).click();
    expect((await download).suggestedFilename()).toBe(`e-bank-${report}.pdf`);
  }
});

test('customer is redirected away from administration', async ({ page }) => {
  await login(page, 'Customer');
  await page.goto('/admin/customers');
  await expect(page).toHaveURL(/unauthorized/);
});

test('credit updates the persisted account balance', async ({ page }) => {
  await login(page, 'Customer');
  await page.goto('/customer/deposit');
  await expect(page.locator('#accountId option')).not.toHaveCount(1);
  const accountId = await page.locator('#accountId option').nth(1).getAttribute('value');
  expect(accountId).toBeTruthy();
  const token = await page.evaluate(() => sessionStorage.getItem('digital-banking-token') || localStorage.getItem('digital-banking-token'));
  const headers = { Authorization: `Bearer ${token}` };
  const beforeResponse = await page.request.get(`/api/accounts/${accountId}`, { headers });
  expect(beforeResponse.ok()).toBe(true);
  const before = await beforeResponse.json();
  await page.getByLabel('Select Account').selectOption(accountId!);
  await page.getByLabel('Amount', { exact: true }).fill('1.25');
  await page.getByLabel('Description').fill(`E2E credit ${Date.now()}`);
  const mutation = page.waitForResponse(r => r.request().method() === 'POST' && r.url().includes('credit'));
  await page.locator('button[type="submit"]').click();
  expect((await mutation).ok()).toBe(true);
  await expect.poll(async () => {
    const after = await (await page.request.get(`/api/accounts/${accountId}`, { headers })).json();
    return Math.round((after.balance - before.balance) * 100);
  }).toBe(125);
});

test('transfer review, concurrent replay and conflicting retry preserve balances', async ({ page }) => {
  await login(page, 'Customer');
  await page.goto('/customer/transfer');
  await expect(page.locator('#fromAccountId option')).not.toHaveCount(1);
  const token = await page.evaluate(() => sessionStorage.getItem('digital-banking-token') || localStorage.getItem('digital-banking-token'));
  const headers = { Authorization: `Bearer ${token}` };
  const accountsResponse = await page.request.get('/api/customer/accounts', { headers });
  expect(accountsResponse.ok()).toBe(true);
  const accounts = (await accountsResponse.json()).filter((a: any) => a.status === 'ACTIVATED');
  expect(accounts.length).toBeGreaterThanOrEqual(2);
  const [source, destination] = accounts;
  await page.getByLabel('From Account', { exact: true }).selectOption(source.id);
  await page.getByLabel('To Account ID', { exact: true }).fill(destination.id);
  await page.getByLabel('Amount', { exact: true }).fill('0.25');
  await page.getByLabel('Description', { exact: true }).fill('E2E transfer review');
  let submitted = 0;
  page.on('request', request => {
    if (request.method() === 'POST' && request.url().endsWith('/transfer')) submitted++;
  });
  await page.getByRole('button', { name: 'Review transfer', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Confirm transfer', exact: true })).toBeEnabled();
  await expect(page.getByLabel('Amount', { exact: true })).toBeDisabled();
  expect(submitted).toBe(0);
  const responsePromise = page.waitForResponse(r => r.request().method() === 'POST' && r.url().endsWith('/transfer'));
  await page.getByRole('button', { name: 'Confirm transfer', exact: true }).click();
  const response = await responsePromise;
  expect(response.ok()).toBe(true);
  const receipt = await response.json();
  const key = response.request().headers()['idempotency-key'];
  expect(key).toBeTruthy();
  await expect(page.getByRole('status')).toContainText(receipt.id);
  const data = response.request().postDataJSON();
  const replayHeaders = { ...headers, 'Idempotency-Key': key };
  const retries = await Promise.all(Array.from({ length: 5 }, () => page.request.post('/api/transactions/transfer', { headers: replayHeaders, data })));
  for (const retry of retries) {
    expect(retry.ok()).toBe(true);
    expect(await retry.json()).toEqual(receipt);
  }
  const conflict = await page.request.post('/api/transactions/transfer', { headers: replayHeaders, data: { ...data, amount: 0.5 } });
  expect(conflict.status()).toBe(409);
  const afterSource = await (await page.request.get(`/api/accounts/${source.id}`, { headers })).json();
  const afterDestination = await (await page.request.get(`/api/accounts/${destination.id}`, { headers })).json();
  expect(Math.round((afterSource.balance - source.balance) * 100)).toBe(-25);
  expect(Math.round((afterDestination.balance - destination.balance) * 100)).toBe(25);
  const invalid = await page.request.post('/api/transactions/transfer', {
    headers: { ...headers, 'Idempotency-Key': randomUUID() }, data: { ...data, destinationAccountId: 'missing-e2e-account' },
  });
  expect(invalid.status()).toBe(404);
  const unchanged = await (await page.request.get(`/api/accounts/${source.id}`, { headers })).json();
  expect(unchanged.balance).toBe(afterSource.balance);
});
